---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: mohitsharma
  become: false
  vars:
    ansible_python_interpreter: /Users/mohitsharma/.ansible-env/bin/python3
    PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  tasks:
    - name: Check if Docker collection is already installed
      ansible.builtin.stat:
        path: "~/.ansible/collections/ansible_collections/community/docker"
      register: docker_collection

    - name: Install required Ansible collections (if not already installed)
      ansible.builtin.command: ansible-galaxy collection install community.docker
      when: not docker_collection.stat.exists

    - name: Pull Docker Image
      community.docker.docker_image:
        name: "iitgmohitsharma/spe_mini_calc:latest"
        source: pull

    - name: Stop and remove existing container if running
      block:
        - name: Stop existing container (if running)
          ansible.builtin.shell: |
            docker stop spe_mini_calc || true
          ignore_errors: yes

        - name: Remove existing container (if running)
          ansible.builtin.shell: |
            docker rm spe_mini_calc || true
          ignore_errors: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: spe_mini_calc
        image: iitgmohitsharma/spe_mini_calc:latest
        state: started
        detach: true
        interactive: true
        tty: true
        recreate: yes